name: Snyk Container
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      security-events: write

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t your/image-to-test .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: your/image-to-test
        args: --file=Dockerfile
    - name: Fix SARIF severity values
      run: |
        sed -i 's/"severity": null/"severity": "unknown"/g' snyk.sarif
    - name: Validate SARIF file
      run: |
        if grep -q '"severity": null' snyk.sarif; then
          echo "Invalid severity value found in SARIF file"
          exit 1
        fi
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
