stages:
  - test

container-scan:
  stage: test
  image:
    name: snyk/snyk:docker
    entrypoint: [""]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.11-dind
  script:
    - docker build -t app:$CI_COMMIT_SHORT_SHA .
    - snyk auth $SNYK_TOKEN
    - snyk container test app:$CI_COMMIT_SHORT_SHA --file=Dockerfile
