name: Snyk Container
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Permiso para leer los archivos del repositorio
      actions: write   # Permiso para ejecutar acciones
      security-events: write  # Permiso para interactuar con la seguridad del repositorio

    steps:
    - uses: actions/checkout@v2  # Checkout del código del repositorio
    - name: Build Docker image
      run: docker build -t your/image-to-test .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: your/image-to-test
        args: --file=Dockerfile
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Aquí se usa el token automáticamente

            
